nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*'] # Replace '*' with specific domains in production
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    paths:
        '^/api/': null
